# Utilizando a biblioteca do Numpy

https://www.youtube.com/watch?v=AGzB7_vsLbE&list=PLjgj6kdf_snaw8QnlhK5f3DzFDFKDU5f4&index=9

In [1]:
#importando a biblioteca
import numpy as np

In [2]:
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])

In [3]:
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])

In [4]:
bmi = np_weight / np_height ** 2

In [5]:
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [18]:
# retorna um valor boleano da comparacao de cada coluna
bmi > 21.80

array([ True, False, False,  True, False])

In [20]:
# retorna o valor da coluna verdadeira
bmi[bmi > 21.80]

array([21.85171573, 24.7473475 ])

In [11]:
# cria uma matrix de 5 colunas e 2 linhas
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79], [65.4, 59.2, 63.6, 88.4, 68.7]])

In [21]:
# seleciona a coluna 3 da linha 1
np_2d[0][2]

1.71

In [22]:
# seleciona a coluna 3
np_2d[0, 2]

1.71

In [23]:
# Seleciona as colunas 2 e 3 de todas as linhas
np_2d[:, 1:3]

array([[ 1.68,  1.71],
       [59.2 , 63.6 ]])

In [24]:
# Todos as colunas da linha 2
np_2d[1, :]

array([65.4, 59.2, 63.6, 88.4, 68.7])

## Usando estatistica com Numpy

In [25]:
# importando o pandas
import pandas as pd

In [29]:
municipios = pd.read_csv(r'https://raw.githubusercontent.com/kelvins/Municipios-Brasileiros/main/csv/municipios.csv')

municipios.head()

codigo_ibge                 nome  latitude  longitude  capital  codigo_uf
0      5200050      Abadia de Goiás -16.75730   -49.4412        0         52
1      3100104  Abadia dos Dourados -18.48310   -47.3916        0         31
2      5200100            Abadiânia -16.19700   -48.7057        0         52
3      3100203               Abaeté -19.15510   -45.4444        0         31
4      1500107           Abaetetuba  -1.72183   -48.8788        0         15

In [30]:
municipios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5570 entries, 0 to 5569
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   codigo_ibge  5570 non-null   int64  
 1   nome         5570 non-null   object 
 2   latitude     5570 non-null   float64
 3   longitude    5570 non-null   float64
 4   capital      5570 non-null   int64  
 5   codigo_uf    5570 non-null   int64  
dtypes: float64(2), int64(3), object(1)
memory usage: 261.2+ KB


In [31]:
municipios[municipios['nome'] == 'Assis Chateaubriand']

codigo_ibge                 nome  latitude  longitude  capital  codigo_uf
411      4102000  Assis Chateaubriand  -24.4168   -53.5213        0         41

In [34]:
np_city = np.array(municipios[['latitude' , 'longitude']])
np_city

array([[-16.7573 , -49.4412 ],
       [-18.4831 , -47.3916 ],
       [-16.197  , -48.7057 ],
       ...,
       [-21.0506 , -50.0552 ],
       [ -3.27014, -45.6553 ],
       [-27.4521 , -51.552  ]])

In [35]:
np_city.shape

(5570, 2)

In [36]:
np.mean(np_city[:, 0])

-16.449143712746856

In [37]:
np.median(np_city[:, 0])

-18.094299999999997

In [38]:
height = np.round(np.random.normal(1.75, 0.20, 5000), 2)
weight = np.round(np.random.normal(60.32, 15, 5000), 2)

In [39]:
np_bmi = np.column_stack((height, weight))

In [40]:
np_bmi.shape

(5000, 2)

In [41]:
np_bmi

array([[ 2.01, 98.62],
       [ 1.95, 85.48],
       [ 1.41, 82.85],
       ...,
       [ 1.74, 76.97],
       [ 1.72, 92.82],
       [ 1.74, 70.92]])

In [48]:
grade = pd.read_json('grade_score.json')
grade.head()

school_name   class  \
0  ABC primary school  Year 1   
1  ABC primary school  Year 1   
2  ABC primary school  Year 1   

                                            students  
0  {'id': 'A001', 'name': 'Tom', 'math': 60, 'phy...  
1  {'id': 'A002', 'name': 'James', 'math': 89, 'p...  
2  {'id': 'A003', 'name': 'Jenny', 'math': 79, 'p...

In [59]:
pd.json_normalize(grade['students'])

id   name  math  physics  chemistry
0  A001    Tom    60       66         61
1  A002  James    89       76         51
2  A003  Jenny    79       90         78