![green-divide](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

_Robson_

> Adriano

**Venancio**

[Sakila Sample Database](https://dev.mysql.com/doc/sakila/en/)

## Training

In [4]:
1 + 3

4

In [ ]:
# this is the reference
# Second commentary

## Part 4 - Exporting to Excel

1. write = pandas.ExcelWrite('filename.xlsx')
2. dataframe.to_excel(write, sheet_name='name')
3. write.save()

## Numpy

High performance, simple, work to linear algebra

In [2]:
import numpy as np


In [5]:
2 ** 20

1048576

In [6]:
8 * (2 ** 20)

8388608

In [7]:
8 * (2 ** 30)

8589934592

In [8]:
8 * 8 * (2 ** 30)

68719476736

In [13]:
np.int8

numpy.int8

In [14]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [15]:
a = np.array([1, 2, 3, 4])

In [16]:
a

array([1, 2, 3, 4])

In [17]:
a[0]

1

In [18]:
a[:2]

array([1, 2])

In [19]:
a[2:]

array([3, 4])

In [21]:
a[[1, -1]]

array([2, 4])

In [22]:
a.dtype

dtype('int32')

In [23]:
np.array(a, dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [24]:
a.dtype

dtype('int32')

In [3]:
a = np.arange(4)

In [4]:
a

array([0, 1, 2, 3])

In [5]:
a * 10

array([ 0, 10, 20, 30])

In [6]:
a += 100

In [7]:
a

array([100, 101, 102, 103])

In [8]:
l = [0, 1, 3, 4]

In [9]:
[i + 10 for i in l]

[10, 11, 13, 14]

In [10]:
a = np.arange(4)

In [12]:
a[[True, False, False, True]]

array([0, 3])

In [13]:
a[[0, 3]]

array([0, 3])

In [18]:
a[a > 1]

array([2, 3])

In [20]:
[a[0], a[-1]]

[0, 3]

In [26]:
a.mean()

1.5

In [17]:
a > 1

array([False, False,  True,  True])

In [27]:
a[a >= a.mean()]

array([2, 3])

In [29]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [30]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 3]
])

In [31]:
A.dot(B)

array([[20, 20],
       [56, 53],
       [92, 86]])

In [32]:
A @ B

array([[20, 20],
       [56, 53],
       [92, 86]])

In [33]:
B.T

array([[6, 4, 2],
       [5, 3, 3]])

In [34]:
B.T @ A

array([[36, 48, 60],
       [38, 49, 60]])

In [35]:
import sys

In [36]:
sys.getsizeof(3)

28

In [37]:
np.dtype(int).itemsize

4

In [42]:
l = list(range(100000))

In [43]:
a = np.arange(100000)

In [44]:
%time np.sum(a ** 2)

Wall time: 0 ns


216474736

In [45]:
%time sum([x ** 2 for x in l])

Wall time: 33.9 ms


333328333350000

## Pandas - Series